[project]
name = "stock-predictor"
version = "1.5.0"
description = "Stock Predictor"
requires-python = ">=3.12"
dependencies = [
    "pandas==3.0.6",
    "numpy==2.5.3",
    "scikit-learn==1.9.1",
    "yfinance==1.7.0",
    "pandas-datareader==0.11.1",
    "requests==2.34.2",
    "pyyaml==6.0.3",
    "tqdm==4.70.1",
    "matplotlib==3.11.2",
    "seaborn==0.13.2",
    "scipy==1.18.1",
    "python-dotenv==1.2.3",
    "google-genai==2.24.0"
]
